---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buckets.codemowers.io
spec:
  group: codemowers.io
  names:
    kind: Bucket
    plural: buckets
    singular: bucket
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.creation.state
      name: Ready
      type: string
    - jsonPath: .spec.capacity
      name: Capacity
      type: string
    - jsonPath: .spec.class
      name: Class
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              capacity:
                pattern: ^[1-9][0-9]*[PTGMK]i?$
                type: string
              class:
                type: string
            required:
            - capacity
            - class
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterbucketclasses.codemowers.io
spec:
  conversion:
    strategy: None
  group: codemowers.io
  names:
    kind: ClusterBucketClass
    plural: clusterbucketclasses
    singular: clusterbucketclass
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Description
      jsonPath: .spec.description
      name: Description
      type: string
    - description: Target namespace
      jsonPath: .spec.targetNamespace
      name: Target namespace
      type: string
    - description: Target cluster
      jsonPath: .spec.targetCluster
      name: Target cluster
      type: string
    - description: Storage class
      jsonPath: .spec.storageClass
      name: Storage class
      type: string
    - description: Ingress class
      jsonPath: .spec.ingressClass
      name: Ingress class
      type: string
    - description: Image
      jsonPath: .spec.podSpec.containers[0].image
      name: Image
      type: string
    - description: Age
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              description:
                type: string
              headlessServiceSpec:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              image:
                type: string
              ingressClass:
                type: string
              podSpec:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              quotaType:
                enum:
                - none
                - fifo
                - hard
                type: string
              replicas:
                type: integer
              secretSpec:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              serviceSpec:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              storageClass:
                type: string
              targetCluster:
                type: string
              targetNamespace:
                type: string
              topologyKey:
                type: string
            required:
            - description
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
