---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secrets.codemowers.io
spec:
  group: codemowers.io
  names:
    kind: Secret
    plural: secrets
    singular: secret
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                mapping:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                        description:
                          Secret key
                      value:
                        type: string
                        description:
                          Secret value with suitable placeholders
                size:
                  default: 32
                  type: integer
                  description: Generated secret length
          required: ["spec"]
